### ISSUE TITLE
When navigating between page in Firefox, I get a blue screen

### ISSUE THREAD

**Issue by stof** [flexbox/CSS-Guidelines#10]
When navigating from the homepage to a chapter in firefox, I'm getting a blue screen (the color of the left bar) instead of seeing the page properly.
This only happens when navigating. If I open the target page in a new tab (or if I force the same tab to load the page fully by pasting the URL in the address bar instead of clicking the link), it works fine. So I suspect it is really to some fancy inter-page animation, which is broken in firefox.

**Comment by flexbox** [comment]
Thanks for the issue :)

**Comment by AlexSwtlsk** [comment]
Still get the issue on firefox 54.0

**Comment by flexbox** [comment]
Fixed!
